In [241]:
import pandas as pd

In [242]:
## read the data
df=pd.read_csv ('survey_results_public.csv')
## to read the seted file
schema_df= pd.read_csv('survey_results_schema.csv')

In [243]:
## set option use for to display columns which we wanna see
pd.set_option('display.max_columns',85)
## set option use for to display rows which we wanna see
pd.set_option('display.max_rows',85)

In [244]:
df.head(5)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [245]:
## access the column
df['ConvertedComp'].head(10)

0         NaN
1         NaN
2      8820.0
3     61000.0
4         NaN
5    366420.0
6         NaN
7         NaN
8     95179.0
9     13293.0
Name: ConvertedComp, dtype: float64

The median is the middle number in a set of data

In [246]:
## median Salary 
df['ConvertedComp'].median()

57287.0

In [247]:
## median of each column
df.median()

C:\Users\abdul\anaconda3\envs\deeplearning\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.

Respondent       44442.0
CompTotal        62000.0
ConvertedComp    57287.0
WorkWeekHrs         40.0
CodeRevHrs           4.0
Age                 29.0
dtype: float64

In [248]:
## gives count, mean, std, min, max etc
df.describe()

,Respondent,CompTotal,ConvertedComp,WorkWeekHrs,CodeRevHrs,Age
count,88883.000000,5.594500e+04,5.582300e+04,64503.000000,49790.000000,79210.000000
mean,44442.000000,5.519014e+11,1.271107e+05,42.127197,5.084308,30.336699
std,25658.456325,7.331926e+13,2.841523e+05,37.287610,5.513931,9.178390
min,1.000000,0.000000e+00,0.000000e+00,1.000000,0.000000,1.000000
25%,22221.500000,2.000000e+04,2.577750e+04,40.000000,2.000000,24.000000
50%,44442.000000,6.200000e+04,5.728700e+04,40.000000,4.000000,29.000000
75%,66662.500000,1.200000e+05,1.000000e+05,44.750000,6.000000,35.000000
max,88883.000000,1.000000e+16,2.000000e+06,4850.000000,99.000000,99.000000

In [249]:
## count the non-missing rows in 'ConvertedComp' Column
df['ConvertedComp'].count()

55823

In [250]:
df['Hobbyist']

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [251]:
df['Hobbyist'].value_counts()

Yes    71257
No     17626
Name: Hobbyist, dtype: int64

In [252]:
df['SocialMedia']

0          Twitter
1        Instagram
2           Reddit
3           Reddit
4         Facebook
           ...
88878      YouTube
88879          NaN
88880          NaN
88881          NaN
88882     WhatsApp
Name: SocialMedia, Length: 88883, dtype: object

In [253]:
df['SocialMedia'].value_counts()

Reddit                      14374
YouTube                     13830
WhatsApp                    13347
Facebook                    13178
Twitter                     11398
Instagram                    6261
I don't use social media     5554
LinkedIn                     4501
WeChat 微信                     667
Snapchat                      628
VK ВКонта́кте                 603
Weibo 新浪微博                     56
Youku Tudou 优酷                 21
Hello                          19
Name: SocialMedia, dtype: int64

In [254]:
## by normalize we get percentage ----> e.g Reddit 17%
df['SocialMedia'].value_counts(normalize=True)

Reddit                      0.170233
YouTube                     0.163791
WhatsApp                    0.158071
Facebook                    0.156069
Twitter                     0.134988
Instagram                   0.074150
I don't use social media    0.065777
LinkedIn                    0.053306
WeChat 微信                   0.007899
Snapchat                    0.007437
VK ВКонта́кте               0.007141
Weibo 新浪微博                  0.000663
Youku Tudou 优酷              0.000249
Hello                       0.000225
Name: SocialMedia, dtype: float64

In [255]:
## value counts for each country
df['Country'].value_counts()

United States        20949
India                 9061
Germany               5866
United Kingdom        5737
Canada                3395
                     ...
Tonga                    1
Timor-Leste              1
North Korea              1
Brunei Darussalam        1
Chad                     1
Name: Country, Length: 179, dtype: int64

In [256]:
## group the result by country
df.groupby(['Country'])

In [257]:
## group the result by country 
## assigning the name to group
country_grp = df.groupby(['Country'])

In [258]:
## all the information of people from pakistan
country_grp.get_group('Pakistan')

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
83,84,I am a developer by profession,No,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Pakistan,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",NaN,2-9 employees,"Designer;Developer, mobile;Educator;Student",3,20,2,Slightly satisfied,Slightly satisfied,Somewhat confident,Yes,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,Solve a brain-teaser style puzzle;Interview wi...,Yes,Office environment or company culture;Opportun...,I was preparing for a job search,PKR,Pakistani rupee,40000.0,Monthly,3468.0,40.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,Less than once per month / Never,Office,Average,"Yes, because I see value in code review",20.0,"No, but I think we should",Not sure,I have some influence,C;C++;C#;Java;Kotlin;PHP;SQL,C#;Java;Kotlin;Objective-C,Firebase;MySQL;SQLite,Firebase;MySQL;Oracle;SQLite,Android;Windows,Android;Windows,ASP.NET,NaN,Unity 3D,Unity 3D,Android Studio;Visual Studio,Windows,Development;Testing;Production;Outside of work...,Not at all,NaN,No,Also Yes,No,WhatsApp,In real life (in person),Screen Name,2016,Multiple times per day,Learn how to do things I didn’t necessarily lo...,More than 10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Daily or almost daily,Yes,Yes,"Yes, definitely",A lot more welcome now than last year,Courses on technologies you're interested in,26.0,Man,No,Straight / Heterosexual,Middle Eastern,No,Too long,Neither easy nor difficult
118,119,I am a developer by profession,No,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Pakistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken a part-time in-person course in programm...,20 to 99 employees,"Developer, back-end;Developer, mobile",10,24,6,Slightly dissatisfied,Slightly dissatisfied,Somewhat confident,No,Not sure,"I’m not actively looking, but I am open to new...",3-4 years ago,NaN,No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,PKR,Pakistani rupee,NaN,Monthly,NaN,35.0,There's no schedule or spec; I work on what se...,Being tasked with non-development work;Not eno...,Less than once per month / Never,Office,A little above average,"Yes, because I was told to do so",10.0,"Yes, it's part of our process","The CTO, CIO, or other management purchase new...",I have little or no influence,C;C++;C#;HTML/CSS;Java;JavaScript;SQL,C;C++;C#;HTML/CSS;Java;JavaScript;Kotlin;Pytho...,Firebase;Microsoft SQL Server;MySQL;SQLite,Firebase;MongoDB;Microsoft SQL Server;MySQL;SQ...,Android;Slack;WordPress,Android;iOS;Slack;WordPress,ASP.NET,Angular/Angular.js;React.js,.NET,Node.js;React Native,Android Studio;Notepad++,Windows,Development,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,No,Facebook,In real life (in person),Username,2010,Multiple times per day,Find answers to specific questions;Learn how t...,More than 10 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Daily or almost daily,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,28.0,Man,No,NaN,NaN,Yes,Appropriate in length,Easy
296,298,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of LOWER quality than prop...",NaN,Pakistan,"Yes, part-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,4,17,Less than 1 year,Slightly dissatisfied,Slightly satisfied,NaN,NaN,NaN,I am actively looking for a job,NA - I am an independent contractor or self em...,Write any code,Yes,Office environment or company culture;Remote w...,I was preparing for a job search,PKR,Pakistani rupee,NaN,Monthly,NaN,35.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,All or almost all the time (I'm full-time remote),Office,Average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have a great deal of influence,HTML/CSS;JavaScript;PHP;SQL;Other(s):,JavaScript;SQL;TypeScript;Other(s):,MySQL;PostgreSQL,DynamoDB;Firebase;MongoDB;MySQL;PostgreSQL;Redis,AWS;Linux;Slack;Windows;WordPress,AWS;Docker;Heroku;Linux;Slack;Windows,ASP.NET;jQuery;React.js;Vue.js,React.js;Vue.js,Node.js,Node.js;React Native,PHPStorm;Sublime Text;Visual Studio,Windows,Development,NaN,NaN,Yes,Yes,No,LinkedIn,Neither,Username,2017,A few times per week,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,23.0,Man,No,NaN,NaN,No,Too long,Neither easy nor difficult
297,299,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed part-time,Pakistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,Academic researcher;Data scientist or machine ...,19,Younger than 5 years,6,Slightly dissatisfied,Slightly dissatisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,NaN,Yes,"Industry that I'd be working in;Languages, fra...","Something else changed (education, award, medi...",PKR,Pakistani rupee,0.0,NaN,NaN,NaN,There's no schedule or spec; I work on what se...,Distracting work environment;Non-work commitme...,"More than half, but not all, the time","Other place, such as a coworking space or cafe",Far below average,No,NaN,NaN,Not sure,I have little or no influence,Assembly;C;C++;Java;Python;SQL,Assembly;C;C++;Python,Microsoft SQL Server,NaN,Android;Arduino;Linux;Raspberry Pi;Windows,Arduino;Linux;Raspberry Pi;Windows,NaN,NaN,TensorFlow;Other(s):,Other(s):,Notepad++;PyCharm,Windows,I do not use containers,Not at all,A passing fad,Yes,Yes,Yes,Facebook,In real life (in person),Username,2011,Daily or almost daily,Find answers to specific questions,3-5 times per week,NaN,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not at all",Somewhat more welcome now than last year,NaN,25.0,Man,No,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Easy
309,311,I am a developer by profession,No,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Pakistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,20 to 99 employees,Academic researcher;Database administrator;Dev...,5,18,Less than 1 year,Neither satisfied nor dissatisfied,Slightly dissatisfied,Somewhat confident,No,Not sure,I am actively looking for a job,Less than a year ago,Write any code;Solve a brain-teaser style puzzle,No,Financial performance or funding status of the...,I was preparing for a job search,PKR,Pakistani rupee,360000.0,Yearly,2600.0,48.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Lack of...,About half the time,Office,A little above average,"Yes, because I see value in code review",5.0,"Yes, it's not part of our process but the deve...",Developers typically have the most influence o...,I have some influence,Assembly;C;C++;C#;HTML/CSS;Java;Python;Scala;SQL,C++;Java;Python;SQL,MongoDB;Microsoft SQL Server;MySQL;SQLite,Cassandra;Firebase;MongoDB;Microsoft SQL Serve...,Arduino;IBM Cloud or Watson;Linux;Raspberry Pi...,Android;Arduino;AWS;Docker;Google Cloud Platfo...,ASP.NET;Django;Express;Spring,Angular/Angular.js;ASP.NET;Django;Express;jQue...,.NET;Node.js,Apache Spark;Hadoop;Node.js,NetBeans;Notepad++;Visual Studio Code,Windows,Development;Testing,Non-currency applications of blockchain,Useful across many domains and could change ma...,Yes,Yes,No,LinkedIn,Online,Login,2014,Daily or almost daily,Find answers to specific questions;Get a sense...,More than 10 times per week,Stack Overflow was slightly faster,0-10 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Industry news about technologies you're intere...,24.0,Man,No,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88310,88862,I am a student who is learning to code,Yes,Less than once per year,"OSS is, on average, of LOWER quality than prop...","Independent contractor, freelancer, or self-em...",Pakistan,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,"Developer, back-end;Developer, embedded applic...",3,18,NaN,NaN,NaN,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",Less than a year ago,NaN,NaN,Industry that I'd be working in;Financial perf...,Re-entry into the workforce,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Java,Java;JavaScript;Swift;Other(s):,Firebase,Firebase;MongoDB;MySQL;Oracle;SQLite,Android;Arduino,Android;Arduino;iOS;MacOS,NaN,React.js,NaN,Node.js;React Native,Android Studio;Xcode,MacOS,Development,NaN,Useful across many domains and could change ma...,Yes,Yes,What?,WhatsApp,Online,UserID,2016,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was slightly faster,31-60 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Somewhat more welcome now than last year,Tech articles written by other developers,21.0,Man,No,Bisexual,NaN,Yes,Too long,Difficult
88353,5439,NaN,Yes,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Pakistan,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,NaN,"Developer, full-stack",2,24,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Java;JavaScript;Objective-C;PHP,NaN,MySQL,NaN,Android;IBM Cloud or Watson;iOS;MacOS;Windows;...,NaN,Express,NaN,Unity 3D,Android Studio,Windows,Production,NaN,A passing fad,Yes,Yes,Yes,Instagram,Online,UserID,2018,I have never visited Stack Overflow (before to...,Meet other people with similar skills or inter...,Less than once per week,Stack Overflow was much faster,31-60 minutes,NaN,NaN,"No, I didn't know that Stack Overflow had a jo...","No, I've heard of them, but I am not part of a...","No, not at all",A lot more welcome now than last year,Industry news about technologies you're intere...,24.0,Woman,Yes,NaN,NaN,No,Too short,Easy
88567,39117,NaN,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",Pakistan,"Yes, part-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,Taken an online course in programming or softw...,NaN,Academic researcher;Data or business analyst;D...,4,18,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C;C++;C#;HTML/CSS;Java;JavaScript;SQL,C#;HTML/CSS;Java;JavaScript;PHP;SQL,NaN,NaN,Android,Android,ASP.NET,NaN,.NET;Xamarin,.NET;Xamarin,Android Studio;Notepad++;Sublime Text;Visual S...,Windows,Development;Testing;Production;Outside of work...,NaN,NaN,Yes,Yes,No,WhatsApp,In real life (in person),Username,2015,Daily or almost daily,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was much faster,31-60 minutes,Yes,Daily or almost daily,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Bisexual;Straight / Heterosexual,East Asian,Yes,Appropriate in length,Easy
88710,60066,NaN,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Pakistan,"Yes, full-time",NaN,I never declared a major,Taken an online course in programming or softw...,NaN,NaN,4,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C++;C#;HTML/CSS;Java;PHP;Python;SQL,C++;C#;HTML/CSS;Java;JavaScript;PHP;Python;SQL,Firebase;MySQL;SQLite,Firebase;MongoDB;MySQL;SQLite,Android;Windows,Android;Docker;Google Cloud Platform;IBM Cloud...,NaN,Angular/Angular.js;Django;React.js;Spring,Unity 3D,Flutter;Node.js;Unity 3D,Android Studio;NetBeans;PyCharm;Visual Studio ...,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,What?,YouTube,In real life (in person),Username,2017,A few times per week,Find answers to specific questions;Meet other ...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,20.0,Man,No,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Easy
88875,88182,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed part-time,Pakistan,NaN,"Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,10 to 19 employees,Academic researcher,1,Younger than 5 years,Less than 1 year,NaN,NaN,Very confident,Not sure,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript,NaN,NaN,NaN,Google Cloud Platform,NaN,Other(s):,NaN,Other(s):,NaN,Android Studio,Windows,Development,NaN,Useful across many domains and could change ma...,Yes,Also Yes,What?,Twitter,Neither,Username,NaN,I have never visited Stack Overflow (before to...,Get a sense of belonging to the developer comm...,Less than once per week,The other resource was slightly faster,60+ minutes,NaN,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Not applicable - I did not use Stack Overflow ...,Courses on technologies you're interested in,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Too short,Neither easy nor difficult

In [259]:
## filter the information of single country
filt = df['Country'] == 'Pakistan'
df.loc[filt]['SocialMedia'].value_counts()

WhatsApp                    266
Facebook                    232
YouTube                     182
LinkedIn                     71
Twitter                      58
Instagram                    41
Reddit                       28
I don't use social media     23
Snapchat                      5
Hello                         1
VK ВКонта́кте                 1
Name: SocialMedia, dtype: int64

In [260]:
country_grp['SocialMedia'].value_counts().head(50)

Country              SocialMedia
Afghanistan          Facebook                     15
                     YouTube                       9
                     I don't use social media      6
                     WhatsApp                      4
                     Instagram                     1
                     LinkedIn                      1
                     Twitter                       1
Albania              WhatsApp                     18
                     Facebook                     16
                     Instagram                    13
                     YouTube                      10
                     Twitter                       8
                     LinkedIn                      7
                     Reddit                        6
                     I don't use social media      4
                     Snapchat                      1
                     WeChat 微信                     1
Algeria              YouTube                      42
                     Facebook                     41
                     Twitter                      14
                     LinkedIn                      9
                     I don't use social media      7
                     Instagram                     7
                     Reddit                        2
                     WhatsApp                      2
Andorra              Facebook                      2
                     I don't use social media      2
                     Reddit                        1
                     Snapchat                      1
                     YouTube                       1
Angola               Twitter                       2
                     Facebook                      1
                     YouTube                       1
Antigua and Barbuda  YouTube                       2
                     Facebook                      1
                     Instagram                     1
                     Twitter                       1
                     VK ВКонта́кте                 1
Argentina            WhatsApp                    202
                     Twitter                      80
                     YouTube                      62
                     Instagram                    53
                     Reddit                       50
                     Facebook                     45
                     I don't use social media     22
                     LinkedIn                     16
Armenia              Facebook                     38
                     YouTube                      23
                     LinkedIn                      5
                     Instagram                     3
Name: SocialMedia, dtype: int64

In [261]:
## percentage of social media for china
country_grp['SocialMedia'].value_counts(normalize=True).loc['China']

SocialMedia
WeChat 微信                   0.670549
YouTube                     0.088186
Weibo 新浪微博                  0.069884
I don't use social media    0.044925
Twitter                     0.044925
Reddit                      0.019967
LinkedIn                    0.018303
Facebook                    0.013311
Instagram                   0.011647
Youku Tudou 优酷              0.011647
WhatsApp                    0.004992
VK ВКонта́кте               0.001664
Name: SocialMedia, dtype: float64

In [262]:
## median salary in diiferent countries
country_grp['ConvertedComp'].median()

Country
Afghanistan                               6222.0
Albania                                  10818.0
Algeria                                   7878.0
Andorra                                 160931.0
Angola                                    7764.0
                                          ...
Venezuela, Bolivarian Republic of...      6384.0
Viet Nam                                 11892.0
Yemen                                    11940.0
Zambia                                    5040.0
Zimbabwe                                 19200.0
Name: ConvertedComp, Length: 179, dtype: float64

In [263]:
## median salargy for germany
country_grp['ConvertedComp'].median().loc['Germany']

63016.0

In [264]:
## mean and median salaries 
country_grp['ConvertedComp'].agg(['median', 'mean'])

                                        median           mean
Country
Afghanistan                             6222.0  101953.333333
Albania                                10818.0   21833.700000
Algeria                                 7878.0   34924.047619
Andorra                               160931.0  160931.000000
Angola                                  7764.0    7764.000000
...                                        ...            ...
Venezuela, Bolivarian Republic of...    6384.0   14581.627907
Viet Nam                               11892.0   17233.436782
Yemen                                  11940.0   16909.166667
Zambia                                  5040.0   10075.375000
Zimbabwe                               19200.0   34046.666667

[179 rows x 2 columns]

In [265]:
## mean and medain salary for canada
country_grp['ConvertedComp'].agg(['median', 'mean']).loc['Canada']

median     68705.000000
mean      134018.564909
Name: Canada, dtype: float64

In [266]:
## how many people from pakistan 'LanguageWokedWith' Python
filt = df['Country'] == 'Pakistan'
df.loc[filt]['LanguageWorkedWith'].str.contains('Python')

83       False
118      False
296      False
297       True
309       True
         ...
88310    False
88353      NaN
88567    False
88710     True
88875    False
Name: LanguageWorkedWith, Length: 923, dtype: object

In [267]:
## count the True value as 1 ... and False as 0
filt = df['Country'] == 'Pakistan'
df.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()

251

In [268]:
## from country group
## error due to coutry_grp is not longer just a series, it a group of series
country_grp['LanguageWorkedWith'].str.contains('Python').sum()

AttributeError: 'SeriesGroupBy' object has no attribute 'str'

In [269]:
## from apply method we do it correct way
## apply on ach series seperate way
country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [270]:
## from apply method we do it correct way
## apply on ach series seperate way
country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [271]:
## how many people respondent on survey from each coutry
country_respondents = df['Country'].value_counts()
country_respondents

United States        20949
India                 9061
Germany               5866
United Kingdom        5737
Canada                3395
                     ...
Tonga                    1
Timor-Leste              1
North Korea              1
Brunei Darussalam        1
Chad                     1
Name: Country, Length: 179, dtype: int64

In [272]:
## from each 'country' how many people know 'Python; 
country_uses_python = country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())
country_uses_python

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [273]:
## 'concat' the 2 series 
python_df = pd.concat([country_respondents, country_uses_python], axis='columns', sort=False)
python_df

                   Country  LanguageWorkedWith
United States        20949               10083
India                 9061                3105
Germany               5866                2451
United Kingdom        5737                2384
Canada                3395                1558
...                    ...                 ...
Tonga                    1                   0
Timor-Leste              1                   1
North Korea              1                   0
Brunei Darussalam        1                   0
Chad                     1                   0

[179 rows x 2 columns]

In [274]:
## rename the column
python_df.rename(columns={'Country': 'Num_Respondents', 'LanguageWorkedWith': 'Num_KnowsPython'}, inplace=True)
python_df

                   Num_Respondents  Num_KnowsPython
United States                20949            10083
India                         9061             3105
Germany                       5866             2451
United Kingdom                5737             2384
Canada                        3395             1558
...                            ...              ...
Tonga                            1                0
Timor-Leste                      1                1
North Korea                      1                0
Brunei Darussalam                1                0
Chad                             1                0

[179 rows x 2 columns]

In [275]:
## % knows python
python_df['Pct(%)_KnowsPython'] = (python_df['Num_KnowsPython']/python_df['Num_Respondents']) * 100
python_df

                   Num_Respondents  Num_KnowsPython  Pct(%)_KnowsPython
United States                20949            10083           48.131176
India                         9061             3105           34.267741
Germany                       5866             2451           41.783157
United Kingdom                5737             2384           41.554820
Canada                        3395             1558           45.891016
...                            ...              ...                 ...
Tonga                            1                0            0.000000
Timor-Leste                      1                1          100.000000
North Korea                      1                0            0.000000
Brunei Darussalam                1                0            0.000000
Chad                             1                0            0.000000

[179 rows x 3 columns]

In [276]:
## % by sorting
python_df.sort_values(by='Pct(%)_KnowsPython', ascending=False, inplace=True)

In [277]:
python_df.head(50)

,Num_Respondents,Num_KnowsPython,Pct(%)_KnowsPython
Sao Tome and Principe,1,1,100.000000
Timor-Leste,1,1,100.000000
Dominica,1,1,100.000000
Niger,1,1,100.000000
Turkmenistan,7,6,85.714286
Mauritania,7,5,71.428571
Guinea,3,2,66.666667
Bahamas,3,2,66.666667
Guyana,3,2,66.666667
Uganda,72,47,65.277778
Iceland,49,30,61.224490
Haiti,5,3,60.000000
Benin,5,3,60.000000
Namibia,5,3,60.000000
"Congo, Republic of the...",7,4,57.142857
Oman,11,6,54.545455
Cuba,30,16,53.333333
Republic of Korea,39,20,51.282051
San Marino,2,1,50.000000
Sierra Leone,2,1,50.000000
Monaco,4,2,50.000000
South Korea,160,80,50.000000
Bhutan,2,1,50.000000
Seychelles,2,1,50.000000
Chile,206,102,49.514563
Finland,546,266,48.717949
Kenya,249,120,48.192771
United States,20949,10083,48.131176
Israel,952,457,48.004202
Ecuador,82,39,47.560976
Taiwan,187,88,47.058824
Montenegro,17,8,47.058824
Mongolia,17,8,47.058824
Switzerland,978,460,47.034765
United Republic of Tanzania,32,15,46.875000
Hong Kong (S.A.R.),188,88,46.808511
Japan,391,182,46.547315
Maldives,13,6,46.153846
Canada,3395,1558,45.891016
Singapore,303,139,45.874587
New Zealand,524,236,45.038168
China,664,297,44.728916
Honduras,27,12,44.444444
France,2391,1054,44.081974
Iraq,39,17,43.589744
Thailand,214,92,42.990654
Democratic Republic of the Congo,7,3,42.857143
Nepal,237,101,42.616034
Estonia,195,82,42.051282
Russian Federation,1694,708,41.794569

In [278]:
## stastics for specific country(Japan)
python_df.loc['Japan']

Num_Respondents       391.000000
Num_KnowsPython       182.000000
Pct(%)_KnowsPython     46.547315
Name: Japan, dtype: float64

In [279]:
## stastics for specific country(Pakistan)
python_df.loc['Pakistan']

Num_Respondents       923.000000
Num_KnowsPython       251.000000
Pct(%)_KnowsPython     27.193933
Name: Pakistan, dtype: float64

## Q. What is the most common education level for people who answer the survey?

In [280]:
df['EdLevel']

0                                Primary/elementary school
1        Secondary school (e.g. American high school, G...
2                 Bachelor’s degree (BA, BS, B.Eng., etc.)
3                 Bachelor’s degree (BA, BS, B.Eng., etc.)
4                 Bachelor’s degree (BA, BS, B.Eng., etc.)
                               ...
88878                            Primary/elementary school
88879                                                  NaN
88880                                                  NaN
88881                                                  NaN
88882                   Professional degree (JD, MD, etc.)
Name: EdLevel, Length: 88883, dtype: object

In [281]:
## what is the most common education level for people who answer the survey
commonEdlevel=df['EdLevel']

In [282]:
commonEdlevel=df['EdLevel'].value_counts()

In [283]:
commonEdlevel

Bachelor’s degree (BA, BS, B.Eng., etc.)                                              39134
Master’s degree (MA, MS, M.Eng., MBA, etc.)                                           19569
Some college/university study without earning a degree                                10502
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     8642
Associate degree                                                                       2938
Other doctoral degree (Ph.D, Ed.D., etc.)                                              2432
Primary/elementary school                                                              1422
Professional degree (JD, MD, etc.)                                                     1198
I never completed any formal education                                                  553
Name: EdLevel, dtype: int64